FPTBook-main/Models/UserRolesViewModel.cs
using FPTBook.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FPTBook.Models
{
    public class UserRolesViewModel
    {
        public string UserId { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public DateTime DOB { get; set; }
        public String Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public IEnumerable<string> Roles { get; set; }

        public static implicit operator UserRolesViewModel(BookUser v)
        {
            throw new NotImplementedException();
        }
    }
}

FPTBook-main/Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FPTBook.Areas.Identity.Data;
using FPTBook.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Controllers
{   
    [Authorize(Roles = "Admin")]
    public class UserRolesController : Controller
    {
        private readonly UserManager<BookUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserRolesController(UserManager<BookUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (BookUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.Name = user.Name;
                thisViewModel.DOB = user.DOB;
                thisViewModel.Address = user.Address;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }
         public async Task<IActionResult> Manage(string userId)
        {
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles.ToList())
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }
         [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
        private async Task<List<string>> GetUserRoles(BookUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
    }
}

FPTBook-main/Views/UserRoles/Manage.cshtml
@model List<ManageUserRolesViewModel>
@{
    ViewData["Title"] = "Manage";
    Layout = "_AdminLayout";
}
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/UserRoles/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage User</a></li>

            <li class=""><a href="/RoleManager/Index"><em class="fa fa-dashboard">&nbsp;</em> Add Role</a></li>

            <li class=""><a href="/Categories/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Category</a></li>

            <li class=""><a href="/Admin/ReportDemo"><em class="fa fa-dashboard">&nbsp;</em> Report</a></li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <form method="post">
        <div class="card">
            <div class="card-header">
                <h2>Manage User Roles</h2>
                Add/Remove Roles for User / @ViewBag.UserName.
            </div>
            <hr>
            <div class="card-body">
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="form-check m-1">
                        <input type="hidden" asp-for="@Model[i].RoleId" />
                        <input type="hidden" asp-for="@Model[i].RoleName" />
                        <input class="form-check-input" type="radio" asp-for="@Model[i].Selected" />
                        <label class="form-check-label" asp-for="@Model[i].Selected">
                            @Model[i].RoleName
                        </label>
                    </div>
                }
                <div asp-validation-summary="All" class="text-danger"></div>
            </div>
            <div class="card-footer">
                <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
                <a asp-action="index" asp-route-id="@ViewBag.userId" class="btn btn-primary"
                    style="width:auto">Cancel</a>
            </div>
        </div>
    </form>
</div>

FPTBook-main/Views/UserRoles/index.cshtml
@using Microsoft.AspNetCore.Identity
@using FPTBook.Areas.Identity.Data

@inject SignInManager<BookUser> SignInManager
@inject UserManager<BookUser> UserManager
@using FPTBook.Models;
@model List<FPTBook.Models.UserRolesViewModel>
@{
    ViewData["Title"] = "Index";
    Layout = "_AdminLayout";
}
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/UserRoles/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage User</a></li>

            <li class=""><a href="/RoleManager/Index"><em class="fa fa-dashboard">&nbsp;</em> Add Role</a></li>

            <li class=""><a href="/Categories/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Category</a></li> 

            <li class=""><a href="/Admin/ReportDemo"><em class="fa fa-dashboard">&nbsp;</em> Report</a></li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
									<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
									asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
										<button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
									</form>
								</li>
        </ul>
    </div>
</nav>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
<h1>User Roles</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Date of Birth</th>
            <th>Home Address</th>
            <th>Email</th>
            <th>Roles</th>
            <th style="text-align: center">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
        <tr>
            <td>@user.Name</td>
            <td>@user.DOB</td>
            <td>@user.Address</td>
            <td>@user.Email</td>
            <td>@string.Join(" , ", user.Roles.ToList())</td>
            <td style="text-align: center">
                <a class="btn btn-primary" asp-controller="UserRoles" asp-action="Manage" asp-route-userId="@user.UserId">Manage Roles</a>
                @* <a class="btn btn-primary" asp-controller="UserRoles" asp-action="Manage" asp-route-userId="@user.UserId">Remove</a> *@
            </td>
        </tr>
        }
    </tbody>
</table>
</div>