FPTBook-main/Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace FPTBook.Models
{
    public class Book
    {
        public int Id { get; set; }
        [Required, StringLength(100)]
        public string? Title { get; set; }
        [Required, Range(0, int.MaxValue)]
        public int Quantity { get; set; }
        [Required, StringLength(500)]
        public string? Description { get; set; }
        public int? AuthorID { get; set; }
        public Author? Author { get; set; }
        public int? PublisherID{ get; set; }
        public Publisher? Publisher { get; set; }
        [Required]
        public string? Poster{get; set;}
        public int CategoryID { get; set; }
        public Category? Category { get; set; }
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }
        [Required, Range(0, int.MaxValue)]
        public decimal Price { get; set; }
    }
}

FPTBook-main/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using FPTBook.Models;
using FPTBook.Utils;
using FPTBook.Areas.Identity.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace FPTBook.Controllers
{
    [Authorize(Roles = "StoreOwner, Admin")]
    public class BooksController : Controller
    {
         private readonly FPTBookIdentityDbContext _context;

        private readonly IWebHostEnvironment hostEnvironment;

        public BooksController(FPTBookIdentityDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            hostEnvironment = environment;
        }

        // GET: Books
        public async Task<IActionResult> Index(string searchString)
        {
            // var fPTBookContext = _context.Book.Include(b => b.Author).Include(b => b.Category).Include(b => b.Publisher);
            // return View(await fPTBookContext.ToListAsync());
            var fPTBookContext = from m in _context.Book.Include(a => a.Category)
                                                    .Include(b => b.Author)
                                                    .Include(c => c.Publisher)
                                                    select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                fPTBookContext = fPTBookContext.Where(s => s.Title!.Contains(searchString));
            }

            return View(await fPTBookContext.ToListAsync());
        }

         // GET: Books/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Books/Create
        public IActionResult Create()
        {
            ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name");
            ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name");
            ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name");
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,AuthorID,PublisherID,Poster,CategoryID,Quantity,ReleaseDate,Price")] Book book, IFormFile myfile, string Title)
        {
            if (ModelState.IsValid)
            {
                if(myfile.Length > 0){
                    string filename = Path.GetFileName(myfile.FileName);
                    string fileType = Path.GetExtension(myfile.FileName).ToLower().Trim();
                    if(fileType != ".jpg" && fileType != ".png"){
                        TempData["Mess"] = "File format not supported. Ony file JPG and PNG";
                        ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name", book.AuthorID);
                        ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name", book.CategoryID);
                        ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name", book.PublisherID);
                        return View(book);
                    }
                    
                    int compare = DateTime.Compare(book.ReleaseDate, DateTime.Today);
                    if(compare > 0){
                        TempData["MessDate"] = "Can't choose a future date";
                        ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name", book.AuthorID);
                        ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name", book.CategoryID);
                        ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name", book.PublisherID);
                        return View(book);
                    }
                    var filePath = Path.Combine(hostEnvironment.WebRootPath, "uploads");
                    string fullPath = filePath + "\\" + filename;
                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        await myfile.CopyToAsync(stream);
                    }
                    book.Poster = filename;
                    _context.Add(book);
                    if(_context.Book.Where(a => a.Title == Title).ToList().Count != 0){
                        return View(book);
                    }
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }  
            }
            ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name", book.AuthorID);
            ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name", book.CategoryID);
            ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name", book.PublisherID);
            return View(book);
        }

              // GET: Books/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name", book.AuthorID);
            ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name", book.CategoryID);
            ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name", book.PublisherID);
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,AuthorID,PublisherID,Poster,CategoryID,Quantity,ReleaseDate,Price")] Book book, IFormFile myfile)
        {
            if (id != book.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    string filename = Path.GetFileName(myfile.FileName);
                    var filePath = Path.Combine(hostEnvironment.WebRootPath, "uploads");
                    string fullPath = filePath + "\\" + filename;
                    using (var stream = new FileStream(fullPath, FileMode.Create))
                    {
                        await myfile.CopyToAsync(stream);
                    }
                    book.Poster = filename;
                    _context.Update(book);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookExists(book.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorID"] = new SelectList(_context.Author, "Id", "Name", book.AuthorID);
            ViewData["CategoryID"] = new SelectList(_context.Category.Where(m => m.Status == "Approve"), "Id", "Name", book.CategoryID);
            ViewData["PublisherID"] = new SelectList(_context.Publisher, "Id", "Name", book.PublisherID);
            return View(book);
        }

              // GET: Books/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Book == null)
            {
                return NotFound();
            }

            var book = await _context.Book
                .Include(b => b.Author)
                .Include(b => b.Category)
                .Include(b => b.Publisher)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Book == null)
            {
                return Problem("Entity set 'FPTBookContext.Book'  is null.");
            }
            var book = await _context.Book.FindAsync(id);
            if (book != null)
            {
                _context.Book.Remove(book);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
         private bool BookExists(int id)
        {
            return (_context.Book?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FPTBook-main/Views/Books/Create.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Create Book";
    Layout = "_StoreOwnerLayout";
}

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/Books/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Book</a></li>

            <li class=""><a href="/Authors/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Author</a></li>

            <li class=""><a href="/Publishers/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Publishsher</a></li>

            <li class=""><a href="/Order/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Order</a></li>

            <li class=""><a href="/Categories/RequestCategory"><em class="fa fa-dashboard">&nbsp;</em>Request Category</a>
            </li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
    <h2>Create Book</h2>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AuthorID" class="control-label">Author</label>
                    <select asp-for="AuthorID" class="form-control" asp-items="ViewBag.AuthorID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="PublisherID" class="control-label">Publisher</label>
                    <select asp-for="PublisherID" class="form-control" asp-items="ViewBag.PublisherID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Poster" class="control-label"></label>
                    <input asp-for="Poster" type="file" name="myfile" class="form-control" />
                    <span asp-validation-for="Poster" class="text-danger"></span>
                    <p style="color: red;">@TempData["Mess"]</p>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryID" class="control-label">Category</label>
                    <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Quantity" class="control-label"></label>
                    <input asp-for="Quantity" min = 0 class="form-control" />
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ReleaseDate" class="control-label"></label>
                    <input asp-for="ReleaseDate" class="form-control" />
                    <span asp-validation-for="ReleaseDate" class="text-danger"></span>
                    <p style="color: red;">@TempData["Mess"]</p>

                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" min = 0 class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <a asp-action="Index"type="button" class="btn btn-warning" >Back to List</a> |  
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FPTBook-main/Views/Books/Delete.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Delete Book";
Layout = "_StoreOwnerLayout";
}

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/Books/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Book</a></li>

            <li class=""><a href="/Authors/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Author</a></li>

            <li class=""><a href="/Publishers/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Publishsher</a></li>

            <li class=""><a href="/Order/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Order</a></li>

            <li class=""><a href="/Categories/RequestCategory"><em class="fa fa-dashboard">&nbsp;</em>Request Category</a>
            </li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    <h2>Delete Book</h2>
    <hr>
    
    <div>
        <h3>Are you sure you want to delete this?</h3>
        <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Publisher.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poster)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poster)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index"type="button" class="btn btn-warning" >Back to List</a> | 
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>
</div>

FPTBook-main/Views/Books/Details.cshtml
@model FPTBook.Models.Book

@{
    ViewData["Title"] = "Details Book";
    Layout = "_StoreOwnerLayout";
}

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/Books/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Book</a></li>

            <li class=""><a href="/Authors/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Author</a></li>

            <li class=""><a href="/Publishers/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Publishsher</a></li>

            <li class=""><a href="/Order/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Order</a></li>

            <li class=""><a href="/Categories/RequestCategory"><em class="fa fa-dashboard">&nbsp;</em>Request
                    Category</a>
            </li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    <h2>Book Details</h2>
    <hr>
    <div>
        <h4>Book</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Author)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Author.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Publisher)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Publisher.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Poster)
            </dt>
            <dd class="col-sm-10">
                <img src="~/uploads/@Html.DisplayFor(model => model.Poster)" width="200" />
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Category)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Category.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ReleaseDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                $@Html.DisplayFor(model => model.Price)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-action="Index" type="button" class="btn btn-warning">Back to List</a>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
        <a asp-action="Edit" asp-route-id="@Model.Id"><button type="button" class="btn btn-success"><span
                    class="material-symbols-outlined"> edit</span></button></a>
    </div>
</div>

FPTBook-main/Views/Books/Index.cshtml
@model IEnumerable<FPTBook.Models.Book>

@{
    ViewData["Title"] = "Index Book";
    Layout = "_StoreOwnerLayout";
}

<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
        <ul class="nav menu">
            <li class="active"><a href="/Books/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Book</a></li>

            <li class=""><a href="/Authors/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Author</a></li>

            <li class=""><a href="/Publishers/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Publishsher</a></li>

            <li class=""><a href="/Order/Index"><em class="fa fa-dashboard">&nbsp;</em> Manage Order</a></li>

            <li class=""><a href="/Categories/RequestCategory"><em class="fa fa-dashboard">&nbsp;</em>Request
                    Category</a>
            </li>
            <br><br><br><br><br><br><br><br>

            <li class="nav-item">
                <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                    asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                    <button id="logout" type="submit" class="nnav-link text-dark">Logout</button>
                </form>
            </li>
        </ul>
    </div>
</nav>
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">

    <h2>Book's Information</h2>
    <hr>
    <p>
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    </p>
    <form asp-controller="Books" asp-action="Index" method="get">
        <p>
            <input type="text" name="SearchString" placeholder="Search By Title" />
            <input class="btn btn-warning" type="submit" value="Search" />
        </p>
    </form>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Author)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Publisher)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Poster)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ReleaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    &ensp;Edit &ensp;&ensp; Details &ensp; Delete
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher.Name)
                    </td>
                    <td>
                        <img src="~/uploads/@Html.DisplayFor(modelItem => item.Poster)" width="200" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                      <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ReleaseDate)
                    </td>
                    <td>
                        $@Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><button type="button" class="btn btn-success"><span
                                class="material-symbols-outlined"> edit</span></button></a> |
                        <a asp-action="Details" asp-route-id="@item.Id"><button type="button" class="btn btn-info"><span
                                class="material-symbols-outlined">visibility</span></button></a> |
                        <a asp-action="Delete" asp-route-id="@item.Id"><button type="button" class="btn btn-danger"><span
                                class="material-symbols-outlined">delete</span></button></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>